### ISSUE TITLE
Add select all in data explore?

### ISSUE THREAD

**Issue by daijiang** [sebpardo/ebirdphylo_app#17]
Hi,
Thanks for this great App! I wonder is it possible to add a "Select All" button in the "explore" page?  This can be useful if users have their own species list already.
Best,
Daijiang

**Comment by sebpardo** [comment]
Hi @daijiang, that shouldn't be too difficult to implement. However, I don't understand how this would be useful; if users have their own species lists already, how does selecting all rows help?

**Comment by daijiang** [comment]
Oh, never mind... thanks!
